### ISSUE TITLE
Verificar problema com xml no Melhor do choro 2 expandido - 19, 20 e 53

### ISSUE THREAD

**Issue by msampaio** [msampaio/umazero#51]
Estes arquivos quebram no processamento com o [song_enumerate](https://github.com/msampaio/choros-contour/blob/master/song_enumerate.py). Verificar internamente no music21. Caso seja trabalhoso encontrar a solução, solicitar reedição.
Em seguida, gerar pdf com eventos enumerados.

```
Warning: can't expand repetitions. <music21.stream.Score 4525078160>
Traceback (most recent call last):
  File "song_enumerate.py", line 43, in <module>
    generate_pdf(f)
  File "song_enumerate.py", line 30, in generate_pdf
    lily.loadObjectFromScore(score)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 274, in loadObjectFromScore
    lpScoreBlock = self.lyScoreBlockFromScore(scoreIn)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 291, in lyScoreBlockFromScore
    lpGroupedMusicList = self.lyGroupedMusicListFromScoreWithParts(scoreIn)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 362, in lyGroupedMusicListFromScoreWithParts
    compositeMusicList.append(self.lyPrefixCompositeMusicFromStream(p))
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 395, in lyPrefixCompositeMusicFromStream
    self.appendObjectsToContextFromStream(part)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 409, in appendObjectsToContextFromStream
    self.appendM21ObjectToContext(el)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 476, in appendM21ObjectToContext
    self.appendObjectsToContextFromStream(thisObject)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 409, in appendObjectsToContextFromStream
    self.appendM21ObjectToContext(el)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 487, in appendM21ObjectToContext
    self.appendContextFromNoteOrRest(thisObject)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 556, in appendContextFromNoteOrRest
    self.setContextForTupletStart(noteOrRest)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 849, in setContextForTupletStart
    if inObj.duration.tuplets is None or len(inObj.duration.tuplets) == 0:
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/duration.py", line 2576, in _getTuplets
    raise DurationException("zero DurationUnits in components")
music21.duration.DurationException: zero DurationUnits in components
```

**Comment by msampaio** [comment]
@AlissonGSilva, eu não consegui resolver o problema com estas músicas expandidas. Você pode reescrevê-las?
Eu encontrei [onde ocorre o problema](https://github.com/msampaio/choros-contour/blob/master/song_enumerate.py#L30), mas não entendi a razão nem como corrigir. Acho mais fácil reeditar as músicas.

**Comment by AlissonGSilva** [comment]
Sim,vou reescrevê-las Marcos.

**Comment by msampaio** [comment]
Valeu, @AlissonGSilva . Depois que fizer me avise aqui.

**Comment by AlissonGSilva** [comment]
Pronto Marcos! Refiz o 19, 20 e 53 do Melhor do choro 2 expandido. Olhe ae se ta dando problema.

**Comment by msampaio** [comment]
@AlissonGSilva , o 20 e 53 estão ok agora, mas o 19 ainda dá erro. O erro está registrado abaixo. Observe nas últimas duas linhas que há algum problema com duração de notas. Você partiu do zero ou copiou da versão sem expansão?

```
Warning: can't expand repetitions. <music21.stream.Score 4427893392>
Traceback (most recent call last):  File "song_enumerate.py", line 43, in <module>
    generate_pdf(f)  File "song_enumerate.py", line 30, in generate_pdf
    lily.loadObjectFromScore(score)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/lily/translate.py", line 269, in loadObjectFromScore
    scoreIn = scoreIn.makeNotation(inPlace = False)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/stream.py", line 12085, in makeNotation
    s.makeNotation(meterStream=meterStream, refStreamOrTimeRange=refStreamOrTimeRange, inPlace=True, bestClef=bestClef, **subroutineKeywords)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/stream.py", line 6143, in makeNotation
    measureStream.makeBeams(inPlace=True)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/stream.py", line 5821, in makeBeams
    beamsList = lastTimeSignature.getBeams(noteStream, measureStartOffset=offset)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/meter.py", line 2952, in getBeams
    archetypeSpan = archetype.positionToSpan(start)
  File "/Users/marcos/.virtualenvs/choros/lib/python2.7/site-packages/music21/meter.py", line 2006, in positionToSpan
    raise MeterException('cannot access qLenPos %s when total duration is %s and ts is %s' % (qLenPos, self.duration.quarterLength, self))
music21.meter.MeterException: cannot access qLenPos 2.0 when total duration is 2.0 and ts is {1/4+1/4}
```

**Comment by AlissonGSilva** [comment]
Copiei da versão sem expansão.
E essas quialteras Marcos?
Vou refazer o arquivo de edição então agora aqui.

**Comment by msampaio** [comment]
O problema deve estar na versão sem expansão. Você pode editar a versão expandida do zero?

**Comment by AlissonGSilva** [comment]
Sim, já comecei a fazer do zero.

**Comment by AlissonGSilva** [comment]
Pronto Marcos, choro 19 refeito do zero, reeditado,reexpandido e com o XML.

**Comment by msampaio** [comment]
@AlissonGSilva , infelizmente ele ainda não está funcionando. Observei dois problemas:
1) Há uma ligadura extra no compasso 2 e nas repetições deste compasso

![Screen Shot 2013-03-24 at 17 13 15](https://f.cloud.github.com/assets/1006488/295883/8db5241a-94bf-11e2-8636-ca48c9ddc714.png)

2) Há uma nota faltando em um compasso e sua repetição (não tenho o número exato do compasso, mas veja o original e a sua edição nas figuras abaixo

![Screen Shot 2013-03-24 at 17 12 40](https://f.cloud.github.com/assets/1006488/295885/967c902e-94bf-11e2-9ce1-b28e965eb5a5.png)

![Screen Shot 2013-03-24 at 17 12 54](https://f.cloud.github.com/assets/1006488/295886/9ac18e28-94bf-11e2-8bb0-4142348dfcf1.png)

Você pode corrigir estes problemas e atualizar o xml?

**Comment by AlissonGSilva** [comment]
Corrigi,acho que agora vai Marcos, olhei todos os compassos.
Olhe ae se vai agora.

**Comment by msampaio** [comment]
@AlissonGSilva , o programa ainda quebra com este choro. Vamos deixar esta tarefa temporariamente em aberto. Já identifiquei que o problema ocorre em [lily.loadObjectFromScore(score)](https://github.com/msampaio/choros-contour/blob/master/song_enumerate.py#L30).

**Comment by msampaio** [comment]
Enumerei o choro 19 manualmente e fiz a segmentação, fechando a tarefa #39.
